name: SCW - Easy Container Redployment
description: Allows you to easy deploy a container on scaleway after you updated the image using only the name of the container
author: Yannick Aaron Lehr
branding:
  icon: 'server'
  color: 'green'
inputs:
  api_version: 
    description: |
      The api version of the container you want to redeploy
    required: true
    default: 'v1beta1'
  region:
    description: |
      The region to use for the api calls
    required: true
    default: 'fr-par'
  container_name:
    description: |
      The name of the container you want to redeploy
    required: true
  api_secret_key:
    description: |
      The api secret key to use for the api calls
    required: true
  organization_id:
    description: |
      The organization id of the container you want to redeploy
    required: false
  project_id:
    description: |
      The project id of the container you want to redeploy
    required: false

runs:
  using: docker
  image: 'Dockerfile' 
  with:
    api_version: version
    region: region
    container_name: container_name
    api_secret_key: api_secret_key
    organization_id: organization_id
    project_id: project_id